version: "3.9"

services:
  backend:
    image: start:latest
    container_name: start-painel
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3007
    networks:
      - network_public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=network_public"

      # HTTPS
      - "traefik.http.routers.start.rule=Host(`start.iecg.com.br` )"
      - "traefik.http.routers.start.entrypoints=websecure"
      - "traefik.http.routers.start.tls.certresolver=letsencrypt"
      - "traefik.http.routers.start.service=start"
      - "traefik.http.services.start.loadbalancer.server.port=3007"

      # HTTP â†’ HTTPS redirect
      - "traefik.http.routers.start-http.rule=Host(`start.iecg.com.br` )"
      - "traefik.http.routers.start-http.entrypoints=web"
      - "traefik.http.routers.start-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  network_public:
    external: true
